---
# -------------------------------------------------------
# install-package.yml
# Installs a package on ALL clients from yum_local repo
# Run: make ansible-install PKG=wget
# -------------------------------------------------------

- name: Install package from local YUM repo
  hosts: clients

  vars:
    pkg_name: "{{ pkg_name }}"    # passed in via -e flag

  tasks:

    - name: Install {{ pkg_name }} from yum_local
      shell: "docker exec {{ inventory_hostname }} dnf install --disablerepo='*' --enablerepo='yum_local' -y {{ pkg_name }}"

    - name: Confirm package is installed
      shell: "docker exec {{ inventory_hostname }} {{ pkg_name }} --version"
      register: pkg_version
      ignore_errors: yes

    - name: Show installed version
      debug:
        var: pkg_version.stdout_lines
