---
# -------------------------------------------------------
# install-package.yml
# Installs a package on ALL clients from yum_local repo
# Run: make ansible-install PKG=wget
# -------------------------------------------------------

- name: Install package from local YUM repo
  hosts: clients
  become: true

  vars:
    pkg_name: "{{ pkg_name }}"    # passed in via -e flag

  tasks:

    - name: Install {{ pkg_name }} from yum_local
      dnf:
        name: "{{ pkg_name }}"
        state: present
        disablerepo: "*"
        enablerepo: "yum_local"

    - name: Confirm package is installed
      command: "{{ pkg_name }} --version"
      register: pkg_version
      ignore_errors: true

    - name: Show installed version
      debug:
        var: pkg_version.stdout_lines
